Más fallos de sangría

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -20,11 +20,11 @@ jobs:
 
       - name: Upload TeXtidote report
         uses: actions/upload-artifact@v2
-          with:
-            name: textidote_report
-              path: report.html
+        with:
+          name: textidote_report
+          path: report.html
 
       - name: Throw error if linter warnings exist
         if: ${{ steps.lint.outputs.num_warnings != 0 }}
-          run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
+        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
   #compile-latex:
